---
- hosts: all
  become: true
  tasks:
    - name: Remove the apache server
      ansible.builtin.yum:
        name: httpd
        state: absent
      when: ansible_distribution == "Amazon"

    - name: Remove the php version
      ansible.builtin.yum:
        name: php
        state: absent
      when: ansible_distribution == "Amazon"
