---
- hosts: all
  become: true
  tasks:
    - name: Update all the packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install the latest apache version
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Add php support for apache
      ansible.builtin.yum:
        name: mod-php
