---
- hosts: all
  become: true
  tasks:
    - name: Update all the packages
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_distribution == "Amazon" and ansible_distribution_version == "1"

    - name: Install the latest apache version
      ansible.builtin.yum:
        name: httpd
        state: latest
